name: Deploy Site To Server

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  main-branch-deploy:
    if: github.repository == 'Aisen60/vue3-h5-template'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SECRETS_HOST }}
          port: ${{ secrets.SECRETS_PORT }}
          username: ${{ secrets.SECRETS_USERNAME }}
          password: ${{ secrets.SECRETS_PASSWORD }}
          script: |
            cd /opt/cxs/vue3-h5-template
            git checkout .
            git pull origin main
            pnpm install
            npm run build
