name: Deploy site by main branch to server

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  main-branch-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /opt/cxs/vue3-h5-template
            git checkout .
            git pull origin main
            pnpm install
            npm run build:deploy
